pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Mufu2005/FlightManagementSystem.git'
            }
        }

        stage('Build') {
            steps {
                bat 'dotnet build'
            }
        }

        stage('Test') {
            steps {
                bat 'dotnet test'
            }
        }

        stage('Publish') {
            steps {
                bat 'dotnet publish -c Release -o out'
            }
        }

        stage('Docker Build & Push') {
            steps {
                bat 'docker build -t yourname/servicename .'
                // Optional Docker Hub push
                // bat 'docker push mufummmmm/FlightService'
            }
        }
    }
}
